[project]
name = "fastapi-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.12",
    "pydantic>=2.11.6",
    "streamlit>=1.45.1",
    "uvicorn>=0.34.3",
]
